/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    JsonComponent: typeof import('./src/components/JsonComponent.vue')['default']
    JsonLayout: typeof import('./src/components/JsonLayout.vue')['default']
  }
}
